export type HistoricalEvent = {
  id: string;
  date: string;
  year: number;
  title: string;
  hazards: string[];
  location: string;
  impact: string;
  summary: string;
  source: string;
  confidence?: 'Verify';
};

const row = (date: string, title: string, hazards: string[], location: string, impact: string, summary: string, source: string, confidence?: 'Verify'): HistoricalEvent => ({
  id: `${date}-${title}`.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  date, year: Number(date.match(/\d{4}/)?.[0] ?? '0'), title, hazards, location, impact, summary, source, confidence,
});

export const historyEvents: HistoricalEvent[] = [
  row('15 Mar 2026', 'Mayurbhanj tornado', ['Tornado'], 'Mayurbhanj, Odisha', '2 deaths · EF2', 'Recent event; the report recommends verifying details against IMD.', 'Vol III · p.4', 'Verify'),
  row('Early 2026', 'Rohtang Tunnel avalanche', ['Avalanche'], 'Manali–Leh highway, Himachal Pradesh', 'Traffic disrupted for hours', 'The report notes an avalanche near the tunnel amid changing winter snowfall patterns.', 'Vol I · p.6', 'Verify'),
  row('2025', 'Cyclone Montha', ['Cyclone'], 'South-east coast', 'Reported low', 'The source marks this recent entry as lower confidence and asks readers to verify it with IMD.', 'Vol II · p.4', 'Verify'),
  row('2024', 'Wayanad landslide and flood', ['Landslide', 'Flood'], 'Wayanad, Kerala', '123+ deaths; later estimates were higher', 'Debris flow through inhabited slopes; the casualty estimate was revised upward in the following weeks.', 'Vol II · p.6'),
  row('2024', 'Cyclone Fengal', ['Cyclone'], 'Tamil Nadu and Puducherry', 'Low', 'Heavy rainfall was more prominent than wind damage.', 'Vol II · p.4'),
  row('2024', 'Cyclone Dana', ['Cyclone'], 'Odisha', 'Low', 'Large evacuation with minimal reported loss.', 'Vol II · p.4'),
  row('2024', 'Cyclone Remal', ['Cyclone'], 'West Bengal and Bangladesh', '~30+ deaths', 'Severe Bay of Bengal cyclone affecting the Bengal coast.', 'Vol II · p.4'),
  row('31 Mar 2024', 'Jalpaiguri tornado', ['Tornado'], 'Jalpaiguri, West Bengal', '5 deaths', 'A recent, well-documented tornado in the report.', 'Vol III · p.4'),
  row('2023', 'Himachal monsoon landslides', ['Landslide', 'Flood'], 'Himachal Pradesh', '~400 deaths for the season', 'Sustained season-long damage rather than one event.', 'Vol II · p.6'),
  row('2023', 'South Lhonak glacial lake outburst flood', ['Flood'], 'Sikkim and West Bengal', '~40 dead and missing', 'The lake burst into the Teesta and destroyed the Chungthang dam.', 'Vol II · p.5'),
  row('2023', 'Cyclone Michaung', ['Cyclone', 'Flood'], 'Andhra Pradesh; severe flooding in Chennai', '~20+ deaths', 'A cyclone-to-urban-flood cascade affected the Chennai region.', 'Vol II · p.4'),
  row('2023', 'Cyclone Biparjoy', ['Cyclone'], 'Jakhau, Gujarat', 'Low', 'An unusually long-lived Arabian Sea system; pre-emptive evacuation reduced loss.', 'Vol II · p.4'),
  row('2023', 'Cyclone Mocha', ['Cyclone'], 'Myanmar and Bangladesh; north-east India affected', 'High regionally', 'Category 5-equivalent system and a near-miss for the Indian mainland.', 'Vol II · p.3'),
  row('2023', 'Joshimath land subsidence', ['Landslide'], 'Joshimath, Uttarakhand', 'Not stated', 'The report links subsidence concerns with drainage, population growth and rapid construction.', 'Vol I · p.5'),
  row('2022–present', 'Barren Island eruption', ['Volcanic'], 'Barren Island, Andaman Sea', 'Ongoing activity reported; ash plumes to ~10,000 ft in Oct 2025', 'The source describes near-continuous activity since January 2022. It records explosive activity continuing as of October 2025, so current status should be rechecked.', 'Vol III · p.3', 'Verify'),
  row('2022', 'Sitrang, Mandous and Asani', ['Cyclone'], 'Andaman & Nicobar, West Bengal and Tamil Nadu', 'Low', 'The report groups these Bay of Bengal storms as a quiet season for India.', 'Vol II · p.3'),
  row('Feb 2021', 'Chamoli avalanche-triggered flash flood', ['Avalanche', 'Flood', 'Landslide'], 'Chamoli, Uttarakhand', '~72 deaths', 'A compound disaster in which an avalanche triggered a destructive flash flood.', 'Vol I · p.5'),
  row('2021', 'Assam (Sonitpur) earthquake', ['Earthquake'], 'Assam', 'Deaths not stated · M6.0', 'NCS attributed the sequence to the Kopili fault zone; multiple aftershocks followed.', 'Vol I · p.4'),
  row('2021', 'Cyclone Yaas', ['Cyclone'], 'Odisha and West Bengal', '~20+ deaths', 'Very severe Bay of Bengal cyclone.', 'Vol II · p.3'),
  row('2021', 'Cyclone Tauktae', ['Cyclone'], 'Una, Gujarat; offshore Mumbai', '~174 deaths', 'The event included the loss of barge P305 offshore Mumbai.', 'Vol II · p.3'),
  row('2021', 'Konkan and Western Ghats flash floods', ['Flood', 'Landslide'], 'Maharashtra, Goa and Karnataka', '~250+ deaths', 'Chiplun and Mahad were severely affected.', 'Vol II · p.6'),
  row('2020', 'Hyderabad urban flood', ['Flood'], 'Hyderabad, Telangana', '~70 deaths', 'Lake-system overflow in a rapidly built-up catchment.', 'Vol II · p.6'),
  row('2020', 'Cyclone Nivar and Burevi', ['Cyclone'], 'Tamil Nadu, Puducherry and Kerala', 'Low', 'Back-to-back late-season Bay of Bengal strikes.', 'Vol II · p.3'),
  row('2020', 'Cyclone Nisarga', ['Cyclone'], 'Alibag, Maharashtra', 'Low', 'A rare near-miss for Mumbai on the west coast.', 'Vol II · p.3'),
  row('2020', 'Cyclone Amphan', ['Cyclone'], 'West Bengal, Odisha and Bangladesh', '~128 deaths', 'A super cyclone at peak intensity; Kolkata and the Sundarbans sustained severe damage.', 'Vol II · p.3'),
  row('2019', 'Cyclone Bulbul', ['Cyclone'], 'West Bengal and Sundarbans', '~40+ deaths', 'Very severe Bay of Bengal cyclone.', 'Vol II · p.3'),
  row('2019', 'Cyclone Vayu', ['Cyclone'], 'Gujarat coast', 'Low', 'Skirted Gujarat and turned away before landfall.', 'Vol II · p.3'),
  row('2019', 'Cyclone Fani', ['Cyclone'], 'Puri, Odisha', '~64 deaths', 'About 1.2 million people were evacuated; the report cites it as an evacuation success.', 'Vol II · p.3'),
  row('2019', 'Multi-state monsoon floods', ['Flood'], 'Karnataka, Maharashtra, Kerala, Bihar and Assam', '~1,600 deaths nationally', 'Multiple states faced crises at the same time.', 'Vol II · p.5'),
  row('2018', 'Kerala floods and landslides', ['Flood', 'Landslide'], 'Kerala', '445–500 deaths', 'Worst Kerala flood since 1924; simultaneous reservoir releases were scrutinized afterward.', 'Vol II · p.5'),
  row('2018', 'Cyclone Gaja', ['Cyclone'], 'Nagapattinam, Tamil Nadu', '~63 deaths', 'Severe storm with heavy agricultural losses in the delta.', 'Vol II · p.3'),
  row('2018', 'Cyclone Titli', ['Cyclone'], 'Odisha and Andhra Pradesh border', '~80+ deaths', 'Very severe storm with an erratic post-landfall track.', 'Vol II · p.3'),
  row('2017', 'Cyclone Ockhi', ['Cyclone'], 'Kerala, Tamil Nadu and Lakshadweep', '~245+ deaths', 'Many victims were fishermen already at sea; the event exposed gaps in warnings to boats.', 'Vol II · p.3'),
  row('2016', 'Manipur earthquake', ['Earthquake'], 'Manipur', 'Deaths not stated · M6.7', 'An event on the Indo-Burman arc.', 'Vol I · p.4'),
  row('2015', 'Chennai floods', ['Flood'], 'Tamil Nadu, Andhra Pradesh and Puducherry', '~470 deaths', 'Northeast monsoon flooding closed Chennai airport and cut off parts of the city.', 'Vol II · p.5'),
  row('12 May 2015', 'Dolakha earthquake', ['Earthquake'], 'Dolakha, Nepal', '~213 deaths · M7.3', 'A major aftershock of the Gorkha earthquake.', 'Vol I · p.4'),
  row('25 Apr 2015', 'Gorkha earthquake', ['Earthquake'], 'Nepal and northern India', '~8,857 deaths · M7.8–8.1', 'Strong shaking reached Bihar and Uttar Pradesh.', 'Vol I · p.4'),
  row('2014', 'Jammu and Kashmir floods', ['Flood'], 'Jammu and Kashmir', '~280 deaths', 'The Jhelum overtopped and Srinagar was submerged for days.', 'Vol II · p.5'),
  row('2014', 'Cyclone Hudhud', ['Cyclone'], 'Visakhapatnam, Andhra Pradesh', '~124 deaths', 'Very severe cyclone causing major damage to a large port city.', 'Vol II · p.3'),
  row('15–17 Jun 2013', 'Kedarnath cloudburst, flood and landslide', ['Flood', 'Landslide'], 'Uttarakhand', '~5,700–6,074 deaths', 'Extreme rainfall destroyed more than 250 villages; the report describes it as a defining Indian landslide disaster.', 'Vol I · p.5; Vol II · p.5'),
  row('2013', 'Cyclone Phailin', ['Cyclone'], 'Gopalpur, Odisha', '~45 deaths', 'Nearly one million people were evacuated; the report calls this a template for modern cyclone response.', 'Vol II · p.3'),
  row('2011', 'Sikkim earthquake', ['Earthquake', 'Landslide'], 'Sikkim', '~111 deaths · M6.9', 'The quake triggered widespread landslides in the Kanchenjunga Conservation Area.', 'Vol I · p.4'),
  row('2008', 'Kosi River avulsion flood', ['Flood'], 'Bihar and Nepal', '434+ deaths', 'The Kosi breached its embankment and changed course, flooding districts without a prior flood history.', 'Vol II · p.5'),
  row('2007', 'Devpuri landslide', ['Landslide'], 'Devpuri, Chamoli, Uttarakhand', 'Deaths not stated', 'A cloudburst-triggered landslide event.', 'Vol I · p.5'),
  row('2005', 'Mumbai urban flood (26 July)', ['Flood'], 'Mumbai, Maharashtra', '1,094 deaths', 'Exceptional single-day rainfall overwhelmed the city drainage system.', 'Vol II · p.5'),
  row('2005', 'Muzaffarabad earthquake', ['Earthquake'], 'Kashmir region', 'Major losses reported · M7.6', 'The western end of the Himalayan arc was struck.', 'Vol I · p.4'),
  row('2004', 'Sumatra–Andaman earthquake and Indian Ocean tsunami', ['Earthquake', 'Tsunami'], 'Tamil Nadu, Andaman & Nicobar, Puducherry, Kerala and Andhra Pradesh', 'At least 10,273 deaths; 5,823 missing', 'The source reports 2.7 million people affected across five states and union territories. Indian Tsunami Early Warning System followed in 2007.', 'Vol I · p.3; Vol III · p.2'),
  row('2003', 'Varunavat slope failure', ['Landslide'], 'Uttarkashi, Uttarakhand', 'Deaths not stated', 'A township-threatening slope failure.', 'Vol I · p.5'),
  row('2002', 'Budha Kedar landslide', ['Landslide'], 'Balganga valley, Uttarakhand', 'Deaths not stated', 'Cloudburst-triggered event.', 'Vol I · p.5'),
  row('2001', 'Bhuj earthquake', ['Earthquake'], 'Kutch, Gujarat', '~20,000 deaths · M7.6–7.9', 'An intraplate earthquake; heavy building losses reached Ahmedabad.', 'Vol I · p.4; Vol II · pp.6–7'),
  row('1999', 'Chamoli earthquake', ['Earthquake'], 'Chamoli, Uttarakhand', '~100–103 deaths · M6.5–6.8', 'The rupture sits at one end of the inferred 1803 rupture patch.', 'Vol I · p.4'),
  row('1999', 'Odisha Super Cyclone (05B)', ['Cyclone'], 'Odisha', '15,000+ deaths', 'Winds around 260 km/h; the disaster led to the Odisha State Disaster Management Authority and modern evacuation doctrine.', 'Vol II · p.3'),
  row('1998', 'Belda tornado', ['Tornado'], 'Near Belda, West Bengal', '250 deaths · F2', 'The report identifies this as the deadliest tornado in the Indian record.', 'Vol III · p.4'),
  row('1998', 'Cyclone at Kandla', ['Cyclone'], 'Kandla, Gujarat', '~10,000 deaths', 'The deadliest Arabian Sea cyclone in the modern Indian record; salt-pan and port workers were heavily affected.', 'Vol II · p.2'),
  row('1998', 'Malpa landslide', ['Landslide'], 'Malpa, Pithoragarh, Uttarakhand', '~300 deaths', 'The entire village was wiped out along the Kali River.', 'Vol I · p.5'),
  row('1997', 'Jabalpur earthquake', ['Earthquake'], 'Jabalpur, Madhya Pradesh', '~38 deaths · M6.0', 'A rare earthquake close to a major city, along the Narmada–Son lineament.', 'Vol I · p.4; Vol II · p.7'),
  row('1996', 'Andhra Pradesh cyclone (Kakinada)', ['Cyclone'], 'Kakinada, Andhra Pradesh', '~1,000+ deaths', 'Heavy losses were reported among fishing communities at sea.', 'Vol II · p.3'),
  row('1994–95', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'Eruption episode', 'One of the documented eruption periods in the report.', 'Vol III · p.3'),
  row('1993', 'Berhampore tornado', ['Tornado'], 'Berhampore, West Bengal', '145 deaths · F2', 'A damaging tornado in the eastern India record.', 'Vol III · p.4'),
  row('29 Sep 1993', 'Latur–Killari earthquake', ['Earthquake'], 'Maharashtra', '~8,000–9,748 deaths · M6.2–6.4', 'The area was classified as a low seismic zone; some villages lost over 30% of their population.', 'Vol I · p.4; Vol II · p.7'),
  row('1993', 'Multi-state flash floods', ['Flood'], 'Seven to eight states', '530 deaths', 'A widely distributed flash-flood event.', 'Vol II · p.5'),
  row('1991', 'Uttarkashi earthquake', ['Earthquake'], 'Uttarakhand', '~768 deaths · M6.6–6.8', 'Tremors reached Delhi; hill terrain hampered access for response teams.', 'Vol I · p.4'),
  row('1991', 'Barren Island resumes erupting', ['Volcanic'], 'Barren Island, Andaman Sea', 'Six-month eruption', 'The volcano resumed activity after roughly 150 years of quiet.', 'Vol III · p.3'),
  row('1990', 'Andhra Pradesh cyclone', ['Cyclone'], 'Machilipatnam region, Andhra Pradesh', '~1,000 deaths', 'A damaging cyclone affecting the Machilipatnam region.', 'Vol II · p.3'),
  row('Aug 1988', 'Bihar–Nepal earthquake', ['Earthquake'], 'Bihar and Nepal', '~1,004–1,091 deaths · M6.6–6.9', 'Dense plains population and building collapse dominated casualties.', 'Vol I · p.4'),
  row('1987', 'Kosi floods', ['Flood'], 'Bihar', '1,399 deaths', 'Riverine flooding after the Kosi overflowed.', 'Vol II · p.5'),
  row('1979', 'Morbi dam burst', ['Flood'], 'Morbi, Gujarat', '1,800–2,500 deaths', 'The Machchhu-2 dam collapsed; the report calls it India’s worst dam disaster.', 'Vol II · p.5'),
  row('16–18 Apr 1978', 'Odisha–West Bengal tornado outbreak', ['Tornado'], 'Odisha and West Bengal', '378+ combined deaths', 'An outbreak sequence rather than a single tornado.', 'Vol III · p.4'),
  row('18 Mar 1978', 'New Delhi tornado', ['Tornado'], 'New Delhi, Delhi', '28+ deaths', 'The event shows the recorded tornado hazard is not confined to eastern India.', 'Vol III · p.4'),
  row('1977', 'Andhra Pradesh (Divi Seema) cyclone', ['Cyclone'], 'Divi Seema, Andhra Pradesh', '~10,000 deaths', 'A super cyclone whose storm surge overran islands in the Krishna delta.', 'Vol II · p.3'),
  row('1971', 'Paradip cyclone', ['Cyclone'], 'Paradip, Odisha', '~10,000 deaths', 'A pre-warning-network cyclone.', 'Vol II · p.3'),
  row('1971', 'Lucknow embankment-failure flood', ['Flood'], 'Lucknow, Uttar Pradesh', '13+ deaths', 'Gomti embankments breached.', 'Vol II · p.5'),
  row('1970', 'Bhola cyclone', ['Cyclone'], 'Bengal delta, mainly East Pakistan', '300,000–500,000 deaths', 'The report describes it as the deadliest tropical cyclone in recorded history.', 'Vol II · p.2'),
  row('1968', 'Darjeeling landslide', ['Landslide'], 'Darjeeling, West Bengal', '>1,000 deaths', 'Flood-triggered failures broke a 60 km road into 91 pieces.', 'Vol I · p.5'),
  row('1967', 'Koynanagar earthquake', ['Earthquake'], 'Koynanagar, Maharashtra', '177 deaths; 2,200+ injured · M6.6', 'Reservoir-triggered seismicity has been proposed, though the cause remains disputed.', 'Vol II · p.6'),
  row('1964', 'Rameswaram–Dhanushkodi cyclone', ['Cyclone'], 'Tamil Nadu', 'Estimates vary widely', 'Dhanushkodi was destroyed and abandoned; a passenger train was swept away.', 'Vol II · p.2'),
  row('1960', 'Lucknow flood', ['Flood'], 'Lucknow, Uttar Pradesh', '16+ deaths', 'Gomti flooding fed by Himalayan rainfall.', 'Vol II · p.5'),
  row('1950', 'Assam–Tibet (Mishmi Hills) earthquake', ['Earthquake'], 'Assam and Tibet', '~4,800 deaths · M8.6–8.7', 'The report calls it the largest recorded quake from continental collision rather than subduction.', 'Vol I · p.3'),
  row('1948', 'Guwahati landslide', ['Landslide'], 'Guwahati, Assam', '~500 deaths', 'Heavy rainfall triggered the event.', 'Vol I · p.5'),
  row('1947', 'Assam earthquake', ['Earthquake'], 'Assam', 'Deaths not stated · M~7.5', 'Strong shaking was felt into Manipur.', 'Vol I · p.4'),
  row('1943', 'Kopili fault-zone earthquake', ['Earthquake'], 'Assam', 'Deaths not stated · M7.3', 'Poorly documented; the source notes it occurred during wartime.', 'Vol I · p.4'),
  row('1943', 'Madras urban and riverine flood', ['Flood'], 'Madras (now Chennai), Tamil Nadu', 'Deaths not stated', 'Six days of rain overflowed the Coovum and Adyar rivers.', 'Vol II · p.5'),
  row('1934', 'Bihar–Nepal earthquake', ['Earthquake'], 'Bihar and Nepal', '10,500–12,000 deaths · M8.0–8.4', 'Munger and Muzaffarpur were largely destroyed; 7,253 deaths were recorded in Bihar.', 'Vol I · p.3'),
  row('1897', 'Shillong Plateau earthquake', ['Earthquake'], 'Assam', '~1,500 deaths · M8.0–8.7', 'Felt over about 650,000 km²; extensive liquefaction occurred in Brahmaputra alluvium.', 'Vol I · p.3'),
  row('4 Apr 1905', 'Kangra earthquake', ['Earthquake'], 'Kangra, Himachal Pradesh', '>20,000 deaths · M7.8–8.6', 'A blind thrust event on the Main Himalayan Thrust; the magnitude was later revised downward.', 'Vol I · p.3'),
  row('1869', 'Cachar earthquake', ['Earthquake'], 'Assam', 'Deaths not stated · M7.4–7.8', 'Associated with the Kopili fault zone.', 'Vol I · p.3'),
  row('1864', 'Calcutta cyclone', ['Cyclone'], 'West Bengal', '~60,000 deaths', 'Storm surge travelled up the Hooghly.', 'Vol II · p.2'),
  row('1839', 'Coringa cyclone', ['Cyclone'], 'Coringa, Andhra Pradesh', '~300,000 deaths', 'Storm surge destroyed the port town, which was never fully rebuilt.', 'Vol II · p.2'),
  row('1838', 'Kolkata tornado', ['Tornado'], 'Kolkata, West Bengal', '215 deaths · F5', 'The report identifies it as the most intense tornado recorded in India.', 'Vol III · p.4'),
  row('1833', 'Kathmandu–Bihar earthquake', ['Earthquake'], 'Kathmandu and Bihar', '~6,500 deaths · M~8.0', 'Historical earthquake on the Himalayan arc.', 'Vol I · p.3'),
  row('1819', 'Kutch (Allah Bund) earthquake', ['Earthquake'], 'Kutch, Gujarat', '~1,500+ deaths · M~8.3', 'Created a fault scarp roughly 16 miles long and 10 feet high.', 'Vol I · p.3; Vol II · p.6'),
  row('1803–04', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'Eruption episode', 'A documented early eruption period in the report.', 'Vol III · p.3'),
  row('1803', 'Garhwal earthquake', ['Earthquake'], 'Near Uttarkashi, Uttarakhand', 'Deaths not stated · M~7.5', 'A major 19th-century Himalayan event; the report notes a blind thrust rupture along the Main Himalayan Thrust.', 'Vol I · p.3'),
  row('1795', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'Eruption episode', 'A documented early eruption period in the report.', 'Vol III · p.3'),
  row('1789', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'Eruption episode', 'A documented early eruption period in the report.', 'Vol III · p.3'),
  row('1787', 'Barren Island eruption record begins', ['Volcanic'], 'Barren Island, Andaman Sea', 'First documented activity in the report', 'The source dates the start of the documented eruption record to 1787.', 'Vol III · p.3'),
  row('1681', 'Narcondam volcanic activity', ['Volcanic'], 'Narcondam, Andaman Sea', 'Last activity reported', 'Narcondam is described as dormant, not extinct; 1681 is the listed last activity.', 'Vol III · p.3'),
  row('1618', 'Bombay earthquake', ['Earthquake'], 'Bombay (Mumbai), Maharashtra', '~2,000 deaths', 'The report describes it as the earliest large recorded event on India’s west coast.', 'Vol II · p.6'),
  row('1555', 'Kashmir–Srinagar earthquake', ['Earthquake'], 'Kashmir', 'Hundreds killed · M7.6–8.0', 'The report describes this as the earliest documented Kashmir event.', 'Vol I · p.3'),
  row('1505', 'Kumaon–Nepal earthquake', ['Earthquake'], 'Kumaon and Lo Mustang', 'M8.7–8.9', 'Magnitude estimate combines paleo-seismic and historical evidence.', 'Vol I · p.3'),
  row('1255', 'Kathmandu earthquake', ['Earthquake'], 'Kathmandu, Nepal', '~1/3 of the kingdom reported lost · M~7.8', 'The report preserves the historical account as an approximate casualty description.', 'Vol I · p.3'),
  row('1883', 'Nepal earthquake', ['Earthquake'], 'Nepal', 'M~7.7', 'Listed as an event at the boundary of the instrumental era.', 'Vol I · p.3'),
  row('1852', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'Eruption episode', 'A documented eruption period in the report.', 'Vol III · p.3'),
  row('2005–07', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'Eruption episode', 'A documented eruption period in the report.', 'Vol III · p.3'),
  row('2017–19', 'Barren Island eruption episode', ['Volcanic'], 'Barren Island, Andaman Sea', 'VEI 2 · moderate in 2017', 'The report groups activity from 2017–19 and rates the 2017 eruption as moderate.', 'Vol III · p.3'),
  row('2003–present', 'Baratang mud-volcano activity', ['Volcanic'], 'Baratang, Andaman & Nicobar Islands', 'Active mud volcanoes', 'The report distinguishes Baratang mud volcanism from a magmatic eruption and describes its hazard as low.', 'Vol III · p.3'),
];

export const historyHazards = ['All events', 'Earthquake', 'Cyclone', 'Flood', 'Landslide', 'Avalanche', 'Tsunami', 'Volcanic', 'Tornado'];
